// <auto-generated />
using System;
using DAL.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(TripAdvisorContext))]
    partial class TripAdvisorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("DAL.Model.Location", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("linkPicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("rateLocation")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("DAL.Model.Opinion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Locationid")
                        .HasColumnType("int");

                    b.Property<double>("rateOpinion")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.HasIndex("Locationid");

                    b.ToTable("Opinion");
                });

            modelBuilder.Entity("DAL.Model.Opinion", b =>
                {
                    b.HasOne("DAL.Model.Location", null)
                        .WithMany("opinionList")
                        .HasForeignKey("Locationid");
                });

            modelBuilder.Entity("DAL.Model.Location", b =>
                {
                    b.Navigation("opinionList");
                });
#pragma warning restore 612, 618
        }
    }
}
